// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFdj_RQKAag3SI4UeNVpkQxer9P8CSXxM',
    appId: '1:993832159889:web:a2726bdffd4265febccd30',
    messagingSenderId: '993832159889',
    projectId: 'devmob-echange-77fde',
    authDomain: 'devmob-echange-77fde.firebaseapp.com',
    storageBucket: 'devmob-echange-77fde.firebasestorage.app',
    measurementId: 'G-31M9Z1R4MZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR-4m32Y60gHEYKjzeiDYZO_w6bMx2a2o',
    appId: '1:993832159889:android:87d2e668a1196196bccd30',
    messagingSenderId: '993832159889',
    projectId: 'devmob-echange-77fde',
    storageBucket: 'devmob-echange-77fde.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_1acgth7I7Q61XhHKo-mpY4x1y2In98A',
    appId: '1:993832159889:ios:ffac46287085ecf4bccd30',
    messagingSenderId: '993832159889',
    projectId: 'devmob-echange-77fde',
    storageBucket: 'devmob-echange-77fde.firebasestorage.app',
    iosBundleId: 'com.example.devmobEchange',
  );
}
